[workspace]
resolver = "2"
members = ["crates/secret-manager"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://codeberg.org/caniko/secret-manager"
authors = ["caniko"]

[workspace.dependencies]
nix-manager-core = { git = "https://codeberg.org/caniko/nix-manager-core.git", rev = "339020858a655a1fdc904ef9ba832706caff039d" }
anyhow = "1"
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
forgejo-api = { version = "0.10", default-features = false, features = ["sync", "rustls-tls"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
toml = "0.9"
url = "2"
walkdir = "2"

[workspace.metadata.crane]
name = "secret-manager"

[profile.release]
lto = true
strip = true
