[ci]
runner = "ubuntu-24.04"
runtime = "nix"
provider = "actions"
platform = "github"
publish_crates = true

[ci.pages]
repo = "caniko/secret-manager"
canonical_domain = "secret-manager.tartanoglu.com"
