//! On-demand rotation for generated agenix secret sources.
//!
//! Shape-agnostic: works for any `.age` source whose Nix declaration carries
//! a `generator`, whether the declaration was rendered by
//! `canix secret ... password` or written by hand. Rotation never observes
//! key material — generation runs inside `agenix generate`, so the operator
//! (and this process) stays zero-knowledge.
//!
//! Failure safety: the existing source is renamed aside before generation.
//! Any failure afterwards restores the backup, so the repo is either rotated
//! or untouched — never left without a working source. The backup is dropped
//! only on full success (generate + validate + stage/rekey).

use anyhow::{Result, anyhow, bail};
use clap::Args;
use std::fs;
use std::path::{Path, PathBuf};

use nix_manager_core::exec;

use crate::io::{display_rel, stage_and_rekey};

/// Suffix for the in-flight rotation backup. Deliberately not `.age`, so
/// agenix globs and `secret list` never pick it up.
const BACKUP_SUFFIX: &str = "rotbak";

#[derive(Args, Debug)]
pub struct RotateArgs {
    /// Repo-relative path to the agenix-tracked .age source to rotate.
    pub secret_path: String,

    /// Skip the trailing `agenix rekey -a`. Generation is touchless; rekey
    /// needs the FIDO2 master key, so split them when batching touches.
    #[arg(long, default_value_t = false)]
    pub no_rekey: bool,

    /// Skip `git add` staging.
    #[arg(long, default_value_t = false)]
    pub no_stage: bool,
}

impl RotateArgs {
    pub fn run(&self) -> Result<()> {
        let repo_root = std::env::current_dir()?;
        let rel = PathBuf::from(&self.secret_path);
        preflight(&repo_root, &rel)?;
        let secret_path = repo_root.join(&rel);
        let backup_path = backup_path_for(&secret_path);

        fs::rename(&secret_path, &backup_path).map_err(|e| {
            anyhow!(
                "could not move {} aside: {e}",
                display_rel(&repo_root, &secret_path)
            )
        })?;

        let outcome = regenerate(&rel)
            .and_then(|()| validate_fresh(&repo_root, &secret_path))
            .and_then(|()| {
                stage_and_rekey(&repo_root, &[secret_path.as_path()], self.no_stage, self.no_rekey)
            });
        if let Err(e) = outcome {
            restore(&secret_path, &backup_path, &repo_root)?;
            return Err(e);
        }

        fs::remove_file(&backup_path).map_err(|e| {
            anyhow!(
                "rotated {}, but could not drop backup {}: {e}",
                display_rel(&repo_root, &secret_path),
                display_rel(&repo_root, &backup_path)
            )
        })?;
        eprintln!(
            "rotated {} (new key material generated by `agenix generate`)",
            display_rel(&repo_root, &secret_path)
        );
        Ok(())
    }
}

fn preflight(repo_root: &Path, rel: &Path) -> Result<()> {
    if rel.is_absolute() {
        bail!(
            "rotate takes a repo-relative path, got {}",
            rel.display()
        );
    }
    if rel.extension().is_none_or(|ext| ext != "age") {
        bail!(
            "rotate expects an .age source, got {}",
            rel.display()
        );
    }
    let secret_path = repo_root.join(rel);
    if !secret_path.is_file() {
        bail!(
            "{} does not exist — create it with `canix secret ... password` first",
            display_rel(repo_root, &secret_path)
        );
    }
    let backup_path = backup_path_for(&secret_path);
    if backup_path.exists() {
        bail!(
            "stale rotation backup {} — a previous rotation was interrupted; inspect it, restore or remove it manually, then retry",
            display_rel(repo_root, &backup_path)
        );
    }
    Ok(())
}

fn backup_path_for(secret_path: &Path) -> PathBuf {
    let mut name = secret_path
        .file_name()
        .map(|s| s.to_os_string())
        .unwrap_or_default();
    name.push(format!(".{BACKUP_SUFFIX}"));
    secret_path.with_file_name(name)
}

/// Same invocation `run_plan` uses for fresh generated secrets. The source
/// was moved aside, so generation sees the create-shaped state.
fn regenerate(rel: &Path) -> Result<()> {
    let rel = rel.to_str().ok_or_else(|| anyhow!("non-utf8 secret path"))?;
    exec::run("agenix", ["generate", "-a", rel]).map_err(|e| {
        anyhow!(
            "{e}\n  hint: rotation needs a `generator` on the secret's Nix declaration (e.g. `generator.script = \"strong-passphrase-64\"`); the previous source was restored"
        )
    })
}

fn validate_fresh(repo_root: &Path, secret_path: &Path) -> Result<()> {
    let meta = fs::metadata(secret_path).map_err(|e| {
        anyhow!(
            "`agenix generate` reported success but {} is missing ({e}); the previous source was restored",
            display_rel(repo_root, secret_path)
        )
    })?;
    if meta.len() == 0 {
        bail!(
            "`agenix generate` wrote an empty {}; the previous source was restored",
            display_rel(repo_root, secret_path)
        );
    }
    Ok(())
}

fn restore(secret_path: &Path, backup_path: &Path, repo_root: &Path) -> Result<()> {
    // Generation failed after the move-aside; put the working source back.
    // If the failed generate left a partial file, remove it first.
    if secret_path.exists() {
        fs::remove_file(secret_path)?;
    }
    fs::rename(backup_path, secret_path).map_err(|e| {
        anyhow!(
            "ROTATION FAILED AND RESTORE FAILED: working source is at {}; move it back to {} manually ({e})",
            display_rel(repo_root, backup_path),
            display_rel(repo_root, secret_path)
        )
    })?;
    eprintln!(
        "rotation failed; restored {}",
        display_rel(repo_root, secret_path)
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::io::TempDir;

    fn repo() -> TempDir {
        TempDir::new().expect("test tempdir")
    }

    fn write_source(dir: &TempDir, name: &str, bytes: &[u8]) -> PathBuf {
        let rel = PathBuf::from(name);
        fs::write(dir.path.join(&rel), bytes).expect("write test source");
        rel
    }

    #[test]
    fn preflight_rejects_non_age_suffix() {
        let repo = repo();
        let rel = write_source(&repo, "token.txt", b"x");
        let err = preflight(&repo.path, &rel).unwrap_err();
        assert!(err.to_string().contains(".age"), "{err:?}");
    }

    #[test]
    fn preflight_rejects_absolute_path() {
        let repo = repo();
        let abs = repo.path.join("token.age");
        let err = preflight(&repo.path, &abs).unwrap_err();
        assert!(err.to_string().contains("repo-relative"), "{err:?}");
    }

    #[test]
    fn preflight_missing_source_names_create_command() {
        let repo = repo();
        let err = preflight(&repo.path, Path::new("age/secrets/root/hosts/atlas/missing.age"))
            .unwrap_err();
        assert!(err.to_string().contains("password"), "{err:?}");
    }

    #[test]
    fn preflight_refuses_stale_backup() {
        let repo = repo();
        let rel = write_source(&repo, "token.age", b"old");
        let backup = backup_path_for(&repo.path.join(&rel));
        fs::write(&backup, b"stale").expect("write stale backup");
        let err = preflight(&repo.path, &rel).unwrap_err();
        assert!(err.to_string().contains("stale rotation backup"), "{err:?}");
    }

    #[test]
    fn backup_path_keeps_sibling_name_without_age_suffix() {
        let path = Path::new("age/secrets/root/hosts/atlas/colibri_atlas_api_key.age");
        assert_eq!(
            backup_path_for(path),
            PathBuf::from("age/secrets/root/hosts/atlas/colibri_atlas_api_key.age.rotbak")
        );
    }

    #[test]
    fn validate_fresh_rejects_missing_and_empty() {
        let repo = repo();
        let missing = repo.path.join("missing.age");
        assert!(validate_fresh(&repo.path, &missing).is_err());
        let empty = repo.path.join("empty.age");
        fs::write(&empty, b"").expect("write empty");
        let err = validate_fresh(&repo.path, &empty).unwrap_err();
        assert!(err.to_string().contains("empty"), "{err:?}");
        let full = repo.path.join("full.age");
        fs::write(&full, b"ciphertext").expect("write full");
        assert!(validate_fresh(&repo.path, &full).is_ok());
    }

    #[test]
    fn restore_roundtrip_preserves_bytes() {
        let repo = repo();
        let rel = write_source(&repo, "token.age", b"working-material");
        let secret_path = repo.path.join(&rel);
        let backup_path = backup_path_for(&secret_path);
        fs::rename(&secret_path, &backup_path).expect("move aside");
        fs::write(&secret_path, b"partial").expect("simulate partial generate");
        restore(&secret_path, &backup_path, &repo.path).expect("restore");
        assert_eq!(fs::read(&secret_path).expect("read"), b"working-material");
        assert!(!backup_path.exists());
    }
}
